name: Dispatch Event Workflow

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Run a script
        run: echo "Workflow triggered by Vela"
